dist: xenial
language: python

matrix:
  include:
    - python: 3.6
      env: TOXENV=py36
    - python: 3.7
      env: TOXENV=py37
    - python: 3.7
      env: TOXENV=docs

install:
  - pip install tox

script:
  - tox

before_deploy:
  - "touch .tox/html/.nojekyll"

deploy:
  provider: pages
  target_branch: gh-pages
  local_dir: .tox/html
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  on:
    branch: master
    condition: $TOXENV == docs
